name: OneForAll for subdomain, port scan and Upload Results

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          ls -alh
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psutil

      - name: install nmap
        run: |
          if [ -f /etc/debian_version ]; then
              # Debian 或 Ubuntu 系统
              echo "检测到 Debian 或 Ubuntu 系统，开始安装 nmap..."
              sudo apt-get update
              sudo apt-get install -y nmap
              if [ $? -eq 0 ]; then
                  echo "nmap 安装成功！"
              else
                  echo "nmap 安装失败，请检查网络或权限。"
                  exit 1
              fi
          elif [ -f /etc/redhat-release ]; then
              # CentOS 或 RHEL 系统
              echo "检测到 CentOS 或 RHEL 系统，开始安装 nmap..."
              sudo yum update -y
              sudo yum install -y nmap
              if [ $? -eq 0 ]; then
                  echo "nmap 安装成功！"
              else
                  echo "nmap 安装失败，请检查网络或权限。"
                  exit 1
              fi
          elif [ -f /etc/arch-release ]; then
              # Arch Linux 系统
              echo "检测到 Arch Linux 系统，开始安装 nmap..."
              sudo pacman -Syu --noconfirm
              sudo pacman -S --noconfirm nmap
              if [ $? -eq 0 ]; then
                  echo "nmap 安装成功！"
              else
                  echo "nmap 安装失败，请检查网络或权限。"
                  exit 1
              fi
          else
              echo "未识别的 Linux 发行版，无法自动安装 nmap。请手动安装。"
              exit 1
          fi
          
          # 验证 nmap 是否安装成功
          nmap --version
          if [ $? -eq 0 ]; then
              echo "nmap 已成功安装并可正常使用。"
          else
              echo "nmap 安装可能存在问题，请检查。"
          fi
      - name: Run onforall
        run: |
          python run.py

      - name: Compress results directory
        run: |
          ls -alh
          tar -czvf result.tar.gz results
          ls -alh
          
      - name: Upload compressed results
        uses: actions/upload-artifact@v4
        with:
          name: oneforall-results
          path: result.tar.gz
          if-no-files-found: error
          retention-days: 7
          compression-level: 6
          overwrite: false
          include-hidden-files: false
    
